import os
import sys

sys.path.insert(0, os.path.abspath(".."))
from config import *

VIDEO_FRAME_RATE = 60

INIT_CAM_DISTANCE = 30
MIN_CAM_DISTANCE = 1e-3
MAX_CAM_DISTANCE = 1e3
ZOOM_FACTOR = .25
MOUSE_SPEED = 100
CAM_LENS_NEAR_FACTOR = .1
CAM_LENS_FAR_FACTOR = 2

MODELS_WIREFRAME_COLOR = .3
MODELS_AMBIENT_LIGHT_COLOR = .1
VISUAL_AMBIENT_LIGHT_COLOR = .8
BACKGROUND_COLOR = (.9, .9, .9)
GRID_COLOR = .35

PHYSICS_FRAME_RATE = 240

SCENARIO_SUCCESS_COLOR = (0, 1, 0, 1)
SCENARIO_TIMEOUT_COLOR = (1, 0, 0, 1)
